package aplikasi;

import java.sql.*;
import javax.swing.JOptionPane;
public class jadwal extends javax.swing.JFrame {
enum StatusJadwal {
    MENUNGGU,
    DITERIMA,
    SELESAI
}
private Connection conn;

    /**
     * Creates new form jadwal
     */
    public jadwal() {
        initComponents();
        conn = connectdata.getConnection();
        loadDokter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        comboDokter = new javax.swing.JComboBox<>();
        comboWaktu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeluhan = new javax.swing.JTextArea();
        btnBatal = new javax.swing.JButton();
        btnBuat = new javax.swing.JButton();
        txttanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 248, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buat Jadwal Konsultasi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 768, 68));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nama Lengkap:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 74, 132, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Alamat:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 110, 132, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tanggal:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 68, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Pilih Dokter:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 146, 132, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Waktu:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Keluhan:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 182, 74, 30));

        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 112, 620, -1));

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 76, 620, -1));

        comboDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 151, -1, -1));

        comboWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00:00", "10:00:00", "13:00:00", "15:00:00", " " }));
        comboWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWaktuActionPerformed(evt);
            }
        });
        jPanel1.add(comboWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 101, -1));

        txtKeluhan.setColumns(20);
        txtKeluhan.setRows(5);
        jScrollPane1.setViewportView(txtKeluhan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 182, 610, 129));

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 109, 41));

        btnBuat.setText("BUAT");
        btnBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 321, 109, 41));

        txttanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 87, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        new mainmenupasien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatActionPerformed
        // TODO add your handling code here:
        try {
    String tanggalStr = txttanggal.getText(); 
    java.sql.Date tanggalSQL = java.sql.Date.valueOf(tanggalStr); 
    
    int idPasien = session.idUser;
    int idDokter = getIdDokterFromCombo(comboDokter.getSelectedItem().toString());
    String waktu = comboWaktu.getSelectedItem().toString();
    String keluhan = txtKeluhan.getText();
    String status = "MENUNGGU";

    String sql = "INSERT INTO jadwal_konsultasi (id_pasien, id_dokter, tanggal, waktu, keluhan, status) VALUES (?, ?, ?, ?, ?, ?)";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setInt(1, idPasien);
    pst.setInt(2, idDokter);
    pst.setDate(3, tanggalSQL);
    pst.setString(4, waktu);
    pst.setString(5, keluhan);
    pst.setString(6, status);

    pst.executeUpdate();
    JOptionPane.showMessageDialog(this, "Jadwal berhasil dibuat!");
} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this, "Format tanggal salah! Gunakan YYYY-MM-DD");
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnBuatActionPerformed

    private void comboWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboWaktuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBuat;
    private javax.swing.JComboBox<String> comboDokter;
    private javax.swing.JComboBox<String> comboWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextArea txtKeluhan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
private void loadDokter() {
    try {
        String sql = "SELECT id_user, nama_lengkap FROM user WHERE role = 'dokter'";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        comboDokter.removeAllItems();
        while(rs.next()) {
            // simpan id dokter sebagai item tersembunyi (opsi sederhana: "id-nama")
            comboDokter.addItem(rs.getInt("id_user") + " - " + rs.getString("nama_lengkap"));
        }
    } catch(SQLException e) {
        JOptionPane.showMessageDialog(this, "Error load dokter: " + e.getMessage());
    }
}
private int getIdDokterFromCombo(String comboItem) throws SQLException {
         String[] parts = comboItem.split(" - ");
        return Integer.parseInt(parts[0]); // ambil id_user
    }
}

