package aplikasi;

import java.sql.*;
import java.awt.Color;
import javax.swing.DefaultListModel;


public class konsultasi extends javax.swing.JFrame {
int idLogin;
int idTarget = 0;
String roleLogin;
    DefaultListModel<String> listModel = new DefaultListModel<>();
    
public konsultasi() {
    this.idLogin = session.idUser;
    this.roleLogin = session.role;
    initComponents();

    listDokter.setModel(listModel);

    if (roleLogin.equals("pasien")) {
        loadDokter();
        jLabel1.setText("Daftar Dokter");
    } else {
        loadPasien();
        jLabel1.setText("Daftar Pasien");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDokter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDokter = new javax.swing.JList<>();
        btnkembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        txtPesan = new javax.swing.JTextField();
        btnkirim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 248, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDokter.setBackground(new java.awt.Color(255, 255, 255));
        panelDokter.setPreferredSize(new java.awt.Dimension(200, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar Dokter");

        listDokter.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDokterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listDokter);

        btnkembali.setText("KEMBALI");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDokterLayout = new javax.swing.GroupLayout(panelDokter);
        panelDokter.setLayout(panelDokterLayout);
        panelDokterLayout.setHorizontalGroup(
            panelDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(panelDokterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDokterLayout.setVerticalGroup(
            panelDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDokterLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(panelDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(430, 350));

        txtChat.setEditable(false);
        txtChat.setColumns(20);
        txtChat.setLineWrap(true);
        txtChat.setRows(5);
        jScrollPane2.setViewportView(txtChat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        txtPesan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesanFocusLost(evt);
            }
        });
        txtPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesanActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 330, 80));

        btnkirim.setText("KIRIM");
        btnkirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkirimActionPerformed(evt);
            }
        });
        jPanel1.add(btnkirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesanFocusGained
        // TODO add your handling code here:
        if(txtPesan.getText().equals("Tulis keluhan anda...")) {
            txtPesan.setText("");
            txtPesan.setForeground(new Color(38,50,56));
        }
    }//GEN-LAST:event_txtPesanFocusGained

    private void txtPesanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesanFocusLost
        // TODO add your handling code here:
        if (txtPesan.getText().isEmpty()) {
            txtPesan.setText("Tulis keluhan anda...");
            txtPesan.setForeground(new Color(150,150,150));
        }
    }//GEN-LAST:event_txtPesanFocusLost

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        if (roleLogin.equals("pasien")) {
            new mainmenupasien().setVisible(true);
        } else {
            new mainmenuDocter().setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void txtPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesanActionPerformed

    private void listDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDokterMouseClicked
        // TODO add your handling code here:
        String selected = listDokter.getSelectedValue();
        if (selected != null) {
            idTarget = Integer.parseInt(selected.split(" - ")[0]);
            loadChat(idLogin, idTarget);
        }
    }//GEN-LAST:event_listDokterMouseClicked

    private void btnkirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkirimActionPerformed
        // TODO add your handling code here:
    String pesan = txtPesan.getText();

    if (pesan.isEmpty() || pesan.equals("Tulis keluhan anda...") || idTarget == 0) {
        return;
    }

    kirimPesan(idLogin, idTarget, pesan);
    txtPesan.setText("");
    loadChat(idLogin, idTarget);       
        
    }//GEN-LAST:event_btnkirimActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnkirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listDokter;
    private javax.swing.JPanel panelDokter;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextField txtPesan;
    // End of variables declaration//GEN-END:variables
private void loadDokter() {
    try {
        Connection conn = connectdata.getConnection();
        String sql = "SELECT id_user, nama_lengkap FROM user WHERE role='dokter'";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        listModel.clear();
        while (rs.next()) {
            listModel.addElement(
                rs.getInt("id_user") + " - " + rs.getString("nama_lengkap")
            );
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }        
    }
private void kirimPesan(int idPengirim, int idPenerima, String pesan) {
    try {
        Connection conn = connectdata.getConnection();
        String sql = "INSERT INTO chat (id_pengirim, id_penerima, pesan) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, idPengirim);
        pst.setInt(2, idPenerima);
        pst.setString(3, pesan);

        pst.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
private void loadChat(int idSaya, int idTarget) {
   try {
        Connection conn = connectdata.getConnection();
        String sql = """
            SELECT id_pengirim, pesan, waktu
            FROM chat
            WHERE (id_pengirim=? AND id_penerima=?)
               OR (id_pengirim=? AND id_penerima=?)
            ORDER BY waktu
        """;

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idSaya);
        pst.setInt(2, idTarget);
        pst.setInt(3, idTarget);
        pst.setInt(4, idSaya);

        ResultSet rs = pst.executeQuery();
        txtChat.setText("");

        while (rs.next()) {
            String pengirim;

            if (rs.getInt("id_pengirim") == idSaya) {
                pengirim = "Saya";
            } else {
                pengirim = roleLogin.equals("pasien") ? "Dokter" : "Pasien";
            }

            txtChat.append(pengirim + " : " + rs.getString("pesan") + "\n");
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
}
private void loadPasien() {
    try {
        Connection conn = connectdata.getConnection();
        String sql = "SELECT id_user, nama_lengkap FROM user WHERE role='pasien'";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        listModel.clear();
        while (rs.next()) {
            listModel.addElement(
                rs.getInt("id_user") + " - " + rs.getString("nama_lengkap")
            );
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

}

